In [39]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [40]:
data=pd.read_csv("D:\\MACHINE LEARNING\\PROJECTS\\Music Reccomendation\\tcc_ceds_music.csv")

In [41]:
data.head()

,Unnamed: 0,artist_name,track_name,release_date,genre,lyrics,len,dating,violence,world/life,...,sadness,feelings,danceability,loudness,acousticness,instrumentalness,valence,energy,topic,age
0,0,mukesh,mohabbat bhi jhoothi,1950,pop,hold time feel break feel untrue convince spea...,95,0.000598,0.063746,0.000598,...,0.380299,0.117175,0.357739,0.454119,0.997992,0.901822,0.339448,0.137110,sadness,1.0
1,4,frankie laine,i believe,1950,pop,believe drop rain fall grow believe darkest ni...,51,0.035537,0.096777,0.443435,...,0.001284,0.001284,0.331745,0.647540,0.954819,0.000002,0.325021,0.263240,world/life,1.0
2,6,johnnie ray,cry,1950,pop,sweetheart send letter goodbye secret feel bet...,24,0.002770,0.002770,0.002770,...,0.002770,0.225422,0.456298,0.585288,0.840361,0.000000,0.351814,0.139112,music,1.0
3,10,pérez prado,patricia,1950,pop,kiss lips want stroll charm mambo chacha merin...,54,0.048249,0.001548,0.001548,...,0.225889,0.001548,0.686992,0.744404,0.083935,0.199393,0.775350,0.743736,romantic,1.0
4,12,giorgos papadopoulos,apopse eida oneiro,1950,pop,till darling till matter know till dream live ...,48,0.001350,0.001350,0.417772,...,0.068800,0.001350,0.291671,0.646489,0.975904,0.000246,0.597073,0.394375,romantic,1.0

In [42]:
data.isnull().sum()

Unnamed: 0                  0
artist_name                 0
track_name                  0
release_date                0
genre                       0
lyrics                      0
len                         0
dating                      0
violence                    0
world/life                  0
night/time                  0
shake the audience          0
family/gospel               0
romantic                    0
communication               0
obscene                     0
music                       0
movement/places             0
light/visual perceptions    0
family/spiritual            0
like/girls                  0
sadness                     0
feelings                    0
danceability                0
loudness                    0
acousticness                0
instrumentalness            0
valence                     0
energy                      0
topic                       0
age                         0
dtype: int64

In [43]:
data.shape

(28372, 31)

In [44]:
data=data.drop(["age","energy","valence","instrumentalness","loudness"],axis=1)

In [45]:
data.shape

(28372, 26)

In [46]:
data.columns

Index(['Unnamed: 0', 'artist_name', 'track_name', 'release_date', 'genre',
       'lyrics', 'len', 'dating', 'violence', 'world/life', 'night/time',
       'shake the audience', 'family/gospel', 'romantic', 'communication',
       'obscene', 'music', 'movement/places', 'light/visual perceptions',
       'family/spiritual', 'like/girls', 'sadness', 'feelings', 'danceability',
       'acousticness', 'topic'],
      dtype='object')

In [47]:
data=data[["artist_name","track_name","release_date","genre","family/spiritual","sadness","romantic",'topic','dating', 'violence', 'world/life']]

In [48]:
data.shape

(28372, 11)

In [49]:
data.head()

,artist_name,track_name,release_date,genre,family/spiritual,sadness,romantic,topic,dating,violence,world/life
0,mukesh,mohabbat bhi jhoothi,1950,pop,0.000598,0.380299,0.017104,sadness,0.000598,0.063746,0.000598
1,frankie laine,i believe,1950,pop,0.051124,0.001284,0.001284,world/life,0.035537,0.096777,0.443435
2,johnnie ray,cry,1950,pop,0.002770,0.002770,0.158564,music,0.002770,0.002770,0.002770
3,pérez prado,patricia,1950,pop,0.001548,0.225889,0.411536,romantic,0.048249,0.001548,0.001548
4,giorgos papadopoulos,apopse eida oneiro,1950,pop,0.029755,0.068800,0.463430,romantic,0.001350,0.001350,0.417772

In [50]:
index_values=data.index

In [51]:
index_values

RangeIndex(start=0, stop=28372, step=1)

In [72]:
index_mukesh = data.index[data['artist_name'] == 'mukesh'].tolist()

KeyError: 'artist_name'

In [53]:
index_mukesh

[0, 24, 33]

In [54]:
data.head()

,artist_name,track_name,release_date,genre,family/spiritual,sadness,romantic,topic,dating,violence,world/life
0,mukesh,mohabbat bhi jhoothi,1950,pop,0.000598,0.380299,0.017104,sadness,0.000598,0.063746,0.000598
1,frankie laine,i believe,1950,pop,0.051124,0.001284,0.001284,world/life,0.035537,0.096777,0.443435
2,johnnie ray,cry,1950,pop,0.002770,0.002770,0.158564,music,0.002770,0.002770,0.002770
3,pérez prado,patricia,1950,pop,0.001548,0.225889,0.411536,romantic,0.048249,0.001548,0.001548
4,giorgos papadopoulos,apopse eida oneiro,1950,pop,0.029755,0.068800,0.463430,romantic,0.001350,0.001350,0.417772

In [55]:
data.describe()

,release_date,family/spiritual,sadness,romantic,dating,violence,world/life
count,28372.000000,28372.000000,28372.000000,28372.000000,28372.000000,28372.000000,28372.000000
mean,1990.236888,0.024150,0.129389,0.048681,0.021112,0.118396,0.120973
std,18.487463,0.051025,0.181143,0.106095,0.052370,0.178684,0.172200
min,1950.000000,0.000284,0.000284,0.000284,0.000291,0.000284,0.000291
25%,1975.000000,0.000957,0.001144,0.000975,0.000923,0.001120,0.001170
50%,1991.000000,0.001645,0.005263,0.001754,0.001462,0.002506,0.006579
75%,2007.000000,0.025498,0.235113,0.042301,0.004049,0.192608,0.197793
max,2019.000000,0.618073,0.981424,0.940789,0.647706,0.981781,0.962105

In [56]:
data["overview"]=data["artist_name"]+" "+data["track_name"]+" "+data["genre"]

In [57]:
data.head()

,artist_name,track_name,release_date,genre,family/spiritual,sadness,romantic,topic,dating,violence,world/life,overview
0,mukesh,mohabbat bhi jhoothi,1950,pop,0.000598,0.380299,0.017104,sadness,0.000598,0.063746,0.000598,mukesh mohabbat bhi jhoothi pop
1,frankie laine,i believe,1950,pop,0.051124,0.001284,0.001284,world/life,0.035537,0.096777,0.443435,frankie laine i believe pop
2,johnnie ray,cry,1950,pop,0.002770,0.002770,0.158564,music,0.002770,0.002770,0.002770,johnnie ray cry pop
3,pérez prado,patricia,1950,pop,0.001548,0.225889,0.411536,romantic,0.048249,0.001548,0.001548,pérez prado patricia pop
4,giorgos papadopoulos,apopse eida oneiro,1950,pop,0.029755,0.068800,0.463430,romantic,0.001350,0.001350,0.417772,giorgos papadopoulos apopse eida oneiro pop

In [58]:
data=data.drop(["artist_name","track_name","genre"],axis=1)

In [59]:
data.head()

,release_date,family/spiritual,sadness,romantic,topic,dating,violence,world/life,overview
0,1950,0.000598,0.380299,0.017104,sadness,0.000598,0.063746,0.000598,mukesh mohabbat bhi jhoothi pop
1,1950,0.051124,0.001284,0.001284,world/life,0.035537,0.096777,0.443435,frankie laine i believe pop
2,1950,0.002770,0.002770,0.158564,music,0.002770,0.002770,0.002770,johnnie ray cry pop
3,1950,0.001548,0.225889,0.411536,romantic,0.048249,0.001548,0.001548,pérez prado patricia pop
4,1950,0.029755,0.068800,0.463430,romantic,0.001350,0.001350,0.417772,giorgos papadopoulos apopse eida oneiro pop

In [60]:
vectorizer=TfidfVectorizer()

In [61]:
feature_vectors=vectorizer.fit_transform(data["overview"])

In [62]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 171259 stored elements and shape (28372, 14352)>
  Coords	Values
  (0, 8535)	0.47626007211345067
  (0, 8352)	0.4901460443797733
  (0, 1301)	0.5097172230707752
  (0, 6533)	0.5097172230707752
  (0, 9774)	0.11536855680551501
  (1, 9774)	0.18442616674381904
  (1, 4769)	0.5649249939399976
  (1, 7053)	0.6298007734648435
  (1, 1216)	0.5001976869050472
  (2, 9774)	0.18596312016585603
  (2, 6574)	0.6822092393400224
  (2, 10255)	0.48214833738308693
  (2, 3043)	0.5172439003565072
  (3, 9774)	0.12957485938200777
  (3, 10063)	0.5724829999851911
  (3, 9840)	0.5724829999851911
  (3, 9395)	0.5724829999851911
  (4, 9774)	0.10070699108895978
  (4, 5118)	0.44494001886677
  (4, 9295)	0.44494001886677
  (4, 647)	0.44494001886677
  (4, 3976)	0.44494001886677
  (4, 9047)	0.44494001886677
  (5, 9774)	0.07751038790567216
  (5, 10255)	0.20096191451997156
  :	:
  (28367, 7653)	0.39490769705103623
  (28367, 8218)	0.36003356500105915
  (28367, 6)	0.7200671300021183
  (28367, 5847)	0.20155132117938135
  (28367, 5967)	0.20185035586949018
  (28368, 13422)	0.24623910552678133
  (28368, 5847)	0.20301918595269255
  (28368, 5967)	0.2033203984627484
  (28368, 12742)	0.3943907746683831
  (28368, 604)	0.4834825903345774
  (28368, 10622)	0.4834825903345774
  (28368, 5953)	0.4834825903345774
  (28369, 13738)	0.4102585383645858
  (28369, 8821)	0.48174291870272196
  (28369, 5847)	0.2795211751275114
  (28369, 5967)	0.27993589098
  (28369, 13947)	0.6656692133299429
  (28370, 13980)	0.42637498700452814
  (28370, 11685)	0.45604830883004344
  (28370, 5847)	0.3050956111935496
  (28370, 5967)	0.30554827094796333
  (28370, 12481)	0.6509848175044408
  (28371, 5847)	0.4112390371735
  (28371, 5967)	0.41184917823991546
  (28371, 6484)	0.8131806125872154

In [63]:
data.head()

,release_date,family/spiritual,sadness,romantic,topic,dating,violence,world/life,overview
0,1950,0.000598,0.380299,0.017104,sadness,0.000598,0.063746,0.000598,mukesh mohabbat bhi jhoothi pop
1,1950,0.051124,0.001284,0.001284,world/life,0.035537,0.096777,0.443435,frankie laine i believe pop
2,1950,0.002770,0.002770,0.158564,music,0.002770,0.002770,0.002770,johnnie ray cry pop
3,1950,0.001548,0.225889,0.411536,romantic,0.048249,0.001548,0.001548,pérez prado patricia pop
4,1950,0.029755,0.068800,0.463430,romantic,0.001350,0.001350,0.417772,giorgos papadopoulos apopse eida oneiro pop

In [64]:
data["overview"]=data["overview"]+" "+data["topic"]

In [65]:
data=data.drop("topic",axis=1)

In [66]:
data.head()

,release_date,family/spiritual,sadness,romantic,dating,violence,world/life,overview
0,1950,0.000598,0.380299,0.017104,0.000598,0.063746,0.000598,mukesh mohabbat bhi jhoothi pop sadness
1,1950,0.051124,0.001284,0.001284,0.035537,0.096777,0.443435,frankie laine i believe pop world/life
2,1950,0.002770,0.002770,0.158564,0.002770,0.002770,0.002770,johnnie ray cry pop music
3,1950,0.001548,0.225889,0.411536,0.048249,0.001548,0.001548,pérez prado patricia pop romantic
4,1950,0.029755,0.068800,0.463430,0.001350,0.001350,0.417772,giorgos papadopoulos apopse eida oneiro pop ro...

In [67]:
feature_vectors

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 171259 stored elements and shape (28372, 14352)>

In [68]:
data.isnull().sum()

release_date        0
family/spiritual    0
sadness             0
romantic            0
dating              0
violence            0
world/life          0
overview            0
dtype: int64

In [69]:
feature_matrix=feature_vectors.todense()

In [70]:
matrix=pd.DataFrame(feature_matrix)